# Generated by Django 6.1 on 2026-08-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pidx',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('FONEPAY', 'FonePay')], default='KHALTI', max_length=20),
        ),
    ]
