# Generated by Django 6.1 on 2026-08-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('location', models.CharField(blank=True, help_text='e.g. Indoor, Patio, 2nd Floor', max_length=100)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('RESERVED', 'Reserved'), ('CLEANING', 'Cleaning')], default='AVAILABLE', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='table_qr/')),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
    ]
